### ISSUE TITLE
Sample is using a deprecated API

### ISSUE THREAD

**Issue by zfoltin** [wirecard/paymentSDK-Android#1]
https://github.com/wirecard/paymentSDK-Android/blob/master/PaymentSDKDemoApp/app/src/main/java/de/wirecard/paymentsdkdemoapp/MainActivity.java#L137

Please update to use the non-deprecated version

**Comment by PaymentSDK** [comment]
Hi,
demo apps are updated. Now they use 2nd generation signature.

**Comment by zfoltin** [comment]
Many thanks for the quick response! Is the v2 signature accepted by the iOS SDK too?

**Comment by PaymentSDK** [comment]
Yes, you can find more info related to iOS SDK here:
https://paymentsdk.github.io/interface_w_d_payment.html#ac86c5ddb29aa1e6ea8415ddc0af87fb8

**Comment by zfoltin** [comment]
Great! Thanks a bunch!
