### ISSUE TITLE
Sample crashes when using CardToken.

### ISSUE THREAD

**Issue by Radu12451** [wirecard/paymentSDK-Android#12]
Hello, 
I modified the sample to generate CardToken objects in order to store them on a web server and use them later. Generating the token works as expected but I have 2 issues using the stored CardToken;

1. App crashes when creating a CardToken and setting a masked account number with a NumberFormatException for "*"

 ```
        String timestamp = SignatureHelper.generateTimestamp();
        String merchantID = "33f6d473-3036-4ca5-acb5-8c64dac862d1";
        String secretKey = "9e0130f6-2e1e-4185-b0d5-dc69079c75cc";
        String requestID = UUID.randomUUID().toString();
        TransactionType transactionType = TransactionType.PURCHASE;
        BigDecimal amount = new BigDecimal(5);
        String currency = "EUR";
        String signature = SignatureHelper.generateSignature(timestamp, merchantID, requestID, transactionType.getValue(), amount, currency, secretKey);
        
        CardToken token = new CardToken();
         //this line causes the crash
        token.setMaskedAccountNumber("550000******0012");
        token.setTokenId("4304509873471003");
        
        CardPayment payment = new CardPayment.Builder()
                .setSignature(signature)
                .setMerchantAccountId(merchantID)
                .setRequestId(requestID)
                .setAmount(amount)
                .setTransactionType(transactionType)
                .setCurrency(currency)
                .setRequestTimeStamp(timestamp)
                .build();

        payment.setCardToken(token);

        new Client(mContext, URL_EE_TEST)
                .startPayment(payment);
```

2. I tried the request without the masked account number and i'm getting the error below:

`Response code: -13d-acquirer:The acquirer is missing a mandatory field.  Resend with all fields correctly entered.  Please check your input or use different card.
500.1086: 3d-acquirer:The acquirer is missing a mandatory field.  Resend with all fields correctly entered.  Please check your input or use different card.`

I'm using the test card below:

VISA | 4012000300001003 | 01/2023 | 003

Thanks, Radu

**Comment by stefan-sedlak** [comment]
@Radu12451 we will have a look on Monday.
Have you tried the latest version 3.2.0?
Best,
Stefan

**Comment by Radu12451** [comment]
I tried now with version 3.2.0 and i can use the masked account number but I'm getting the exact error as above.

**Comment by PaymentSDK** [comment]
@Radu12451 The card you are using is 3DSecure capable, which means you should also set card payment's field _attempt3d_ to _true_.

**Comment by Radu12451** [comment]
Hello,

I tried and nothing changes. Were you able to replicate my problem?

Thanks

**Comment by stefan-sedlak** [comment]
Hi @Radu12451 ,
we are able to reproduce the issue.
We will fix MAID configuration at gateway..

Meanwhile please continue your integration with non-3D merchant account:
String merchantID = "9105bb4f-ae68-4768-9c3b-3eda968f57ea";
String secretKey = "d1efed51-4cb9-46a5-ba7b-0fdc87a66544";
from integration perspective there is no change.

Best,
Stefan

**Comment by Radu12451** [comment]
Hello @stefan-sedlak ,

I'll do that. Thanks for your help.

**Comment by stefan-sedlak** [comment]
Hi @Radu12451 ,

here you are - 3DS merchant account:
String merchantID = "cad16b4a-abf2-450d-bcb8-1725a4cef443";
String secretKey = "b3b131ad-ea7e-48bc-9e71-78d0c6ea579d";

We verified that 3DS works with:
- no card data (collecting by SDK)
- card-token

Best,
Stefan

**Comment by Radu12451** [comment]
Hello,

It works as expected.

Thanks

**Comment by Radu12451** [comment]
Hello @stefan-sedlak ,

Is it possible to make a token payment without forcing the user to input his CVC and without showing the 3dSecure password window? The response from in the SDK states that the security code was not provided when using 

.setRequireSecurityCode(true);

Thanks,
Radu

**Comment by stefan-sedlak** [comment]
Hi @Radu12451 ,
for recurring payment (card token) without CVC/3DS
I recommend to use gateway [REST API](https://document-center.wirecard.com/display/PTD/purchase#purchase-purchaseUsingaToken) from your server.

No need to use SDK as no user action is required by SDK in this case.

Best,
Stefan
