### ISSUE TITLE
AAPT:No resource found that matches the given name

### ISSUE THREAD

**Issue by JoaoRSilverio** [wirecard/paymentSDK-Android#14]
Hi ,
Im buidling a react-native wrapper for the android SDK and I'm getting the following build errors:

`.gradle/caches/transforms-1/files-1.1/core-3.2.0.aar/35d1273aa39a61a4435e7c8b8aa90adb/res/values/values.xml:153:5-156:13: AAPT: No resource found that matches the given name: attr 'errorTextAppearance'`
`.gradle/caches/transforms-1/files-1.1/core-3.2.0.aar/35d1273aa39a61a4435e7c8b8aa90adb/res/values/values.xml:153:5-156:13: AAPT: No resource foun
d that matches the given name: attr 'hintTextAppearance'.`

build.gradle:

`apply plugin: 'com.android.library'
buildscript {

    repositories {

        jcenter()
        google()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven {
            url 'https://maven.fabric.io/public'
        }

    }

    dependencies {

        classpath 'com.google.gms:google-services:4.0.1'
        classpath 'com.android.tools.build:gradle:3.1.3'
    }

}
android {

    compileSdkVersion 27
    defaultConfig {
        multiDexEnabled true
        minSdkVersion 19
        targetSdkVersion 27
        versionCode 1
        versionName "1.0.8"
    }
    lintOptions {
        abortOnError false
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

}
ext{

    wirecardEcomLibraryVersion = "3.2.0"

}
repositories {

    jcenter()
    mavenCentral()
    maven {
        url  "https://dl.bintray.com/wirecard/ecom-android"
    }
    google()
    maven { url "https://jitpack.io" }

}
dependencies {

    compileOnly'com.facebook.react:react-native:0.57.2'
    api 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:support-annotations:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'com.android.support:design:27.1.1'
    implementation 'io.reactivex.rxjava2:rxkotlin:2.2.0'
    implementation ("com.wirecard.ecom:card:$wirecardEcomLibraryVersion"){
        exclude group:'com.android.support'
    }

}`
gradle distribution:
`gradle-4.10.1-all.zip`
I suspect that this is related with the buildTools version but i couldn't find a solution yet. 
Any help would be appreciated .
Thank you for your time.

**Comment by stefan-sedlak** [comment]
Hi @JoaoRSilverio ,

It will take a time to reproduce the issue as we have no experience with react-native.
It is quite a big for immediate response. We will spend a time in next sprint.

Best,
Stefan

**Comment by stefan-sedlak** [comment]
Hi @JoaoRSilverio ,
meanwhile we released 3.3.0
we upgraded build tools and gradle plugin versions.

Could you please check again?
We could be lucky :)

Thanks,
Stefan

**Comment by JoaoRSilverio** [comment]
Thank you for your answer.
I managed to solve the issue it was caused by the build resolving to diferent version of support-v4 and support-v7 then expected in the main app that imports this library. I also changed the appcompat version in the lib 
`dependencies {
    compileOnly'com.facebook.react:react-native:0.57.2'
    implementation "com.wirecard.ecom:card:$wirecardEcomLibraryVersion"
    implementation 'com.android.support:appcompat-v7:27.0.0'

    // #TODO implement other payment methods besides card.
    //implementation 'com.github.wirecard:paymentSDK-Android:3.1.0-cardScannerDisabled'
    //implementation "com.wirecard.ecom:sepa:$wirecardEcomLibraryVersion"
    //implementation "com.wirecard.ecom:zapp:$wirecardEcomLibraryVersion"
    //implementation "com.wirecard.ecom:paypal:$wirecardEcomLibraryVersion"
    //implementation "com.wirecard.ecom:google-pay:$wirecardEcomLibraryVersion"
}` , I'll try to make a example-app with the issue

**Comment by stefan-sedlak** [comment]
Thanks! We will improve integration doc!

**Comment by grifotv** [comment]
@JoaoRSilverio I'm also looking into React Native solutions for Wirecard payments. I'd like to talk to you, maybe we could collaborate :) What is you Twitter account?
