### ISSUE TITLE
onObserve<PaymentResponse> never called in Fragment

### ISSUE THREAD

**Issue by squeeish** [wirecard/paymentSDK-Android#15]
Hello, I have implemented `com.wirecard.ecom.util.Observer` in my Fragment as follows:
```
class RegisterCreditCardFragment: BaseFragment(), Observer<PaymentResponse> {
....
override fun onObserve(eventMessage: PaymentResponse) {
        Timber.d("eventMessage $eventMessage")
        viewModel.processPaymentResponse(eventMessage)
    }
....
```
However, onObserve is never called, even after receiving a successful response from Wirecard. However, it works in an Activity. Is it possible for it to work in a Fragment?

**Comment by PaymentSDK** [comment]
Hi,

Observer currently works only in activities. My advice is to implement Observer in your parent activity of the fragment and pass the result to fragment afterwards.
Functionality as described in your e-mail will be implemented in one of future releases.
Thanks and regards,

Ivan

**Comment by squeeish** [comment]
Thanks.
