### ISSUE TITLE
Account holder information not sent when tokenizing

### ISSUE THREAD

**Issue by squeeish** [wirecard/paymentSDK-Android#16]
Hi,

I'm using `implementation 'com.wirecard.ecom:card:3.3.1'`

I'm tokenizing a card via `CardBundle` obtained from `AnimatedCardFieldFragment`.

In `CardBundle`, I see that `lastName` is mapped onto the cardholder value (btw why is `cardSecurityCode` null when I have entered in a security code?). I pass this `CardBundle` into a `CardFieldPayment` builder and call `startPayment` on the Wirecard Client instance.

Upon inspecting the contents that startPayment sends to Wirecard:

```
<payment xmlns="http://www.elastic-payments.com/schema/payment">
   <cancel-redirect-url>https://cancel.mobile.wirecard.com</cancel-redirect-url>
   <card>
      <account-number>5413330300001006</account-number>
      <card-type>mastercard</card-type>
      <expiration-month>01</expiration-month>
      <expiration-year>2023</expiration-year>
   </card>
   <merchant-account-id>e8df8b8e-4e2a-11e9-8646-d663bd873d93</merchant-account-id>
   <payment-methods>
      <payment-method name="creditcard"/>
   </payment-methods>
   <request-id>83a8bc5d-afce-4b5c-a85c-b6067a14e3e7</request-id>
   <requested-amount currency="SGD">1</requested-amount>
   <transaction-type>tokenize</transaction-type>
</payment>
```

You can see that `<account-holder>` information is not present at all. Is this by design?

**Comment by squeeish** [comment]
In addition, `card-security-code` is also not sent. However, it's sent in the iOS SDK.

**Comment by stefan-sedlak** [comment]
Hi @squeeish , we started investigation.
It seems to me very unlikely, I will come back ASAP with a result.
Best,
Stefan

**Comment by stefan-sedlak** [comment]
Hi @squeeish ,
`card-security-code` issue was confirmed for `AnimatedCardFieldFragment` 
`account-holder` is still investigated.
However we will provide hotfix.
ETA next week.
Best,
Stefan

**Comment by squeeish** [comment]
Hi @stefan-sedlak thanks! Looking forward to it.

**Comment by stefan-sedlak** [comment]
Hi @squeeish , we provided [3.3.2](https://bintray.com/wirecard/ecom-android/card/3.3.2#release)
please verify the fix.
Best,
Stefan

**Comment by squeeish** [comment]
Hi @stefan-sedlak thanks! It's fixed.

For reference the new request now looks like:
```
<payment xmlns="http://www.elastic-payments.com/schema/payment"> 
	<account-holder> 
		<last-name>Terence</last-name> 
	</account-holder> 
	<cancel-redirect-url>https://cancel.mobile.wirecard.com</cancel-redirect-url> 
	<card> 
		<account-number>5413330300001006</account-number> 
		<card-security-code>123</card-security-code> 
		<card-type>mastercard</card-type> 
		<expiration-month>12</expiration-month> 
		<expiration-year>2023</expiration-year> 
	</card> 
	<merchant-account-id>e35100c6-4e2a-11e9-8646-d663bd873d93</merchant-account-id> 
	<payment-methods> 
		<payment-method name="creditcard" /> 
	</payment-methods> 
	<request-id>5732788f-a986-46c1-bf34-d85cc96e0ee2</request-id> 
	<requested-amount currency="SGD">1</requested-amount> 
	<transaction-type>tokenize</transaction-type> 
</payment>
```
