### ISSUE TITLE
Response code:General error occurred

### ISSUE THREAD

**Issue by chetan1011** [wirecard/paymentSDK-Android#20]
Response code: -1General error occurred
occur in call back method of activity android please provide me a solution

**Comment by stefan-sedlak** [comment]
Hi @chetan1011 ,
could you please provide more details?
SDK version and some integration details.
Thanks,
Stefan

**Comment by chetan1011** [comment]
> Hi @chetan1011 ,
> could you please provide more details?
> SDK version and some integration details.
> Thanks,
> Stefan

Thanks for quick and fast replay.
SDK version: 
**implementation "com.wirecard.ecom:card:3.3.0"**

As I test/checked in testing server it's working fine.
and got a response like;
**Response code: 0
    201.0000: 3d-acquirer:The resource was successfully created.200.1084: 3d-acquirer:Proof of authentication attempt was generated.**

**But In live/Production : "https://api.wirecard.com"
Error: Response code: -1General error occurred**

**Comment by stefan-sedlak** [comment]
Hi @chetan1011 ,
please upgrade to to most recent 3.3.5 I guess fix in 3.3.3 will help.
Best,
Stefan

**Comment by chetan1011** [comment]
Hi @stefan-sedlak 

I have upgrade payment SDK library 3.30 to 3.3.5. but still, I face the same issue.

Error: Response code: -1General error occurred

****=> payment data**
   val cardPayment = CardPayment.Builder()
            .setSignature(signature)
            .setMerchantAccountId(merchantID)
            .setRequestId(requestID)
            .setAmount(amount)
            .setTransactionType(transactionType)
            .setCurrency(currency)
            .build()
        cardPayment.requireManualCardBrandSelection = true
        cardPayment.animatedCardPayment = true
**=> call start payment**
    Client((activity as HomeActivity), Constants.PAYMENT_URL, Constants.REQUEST_TIMEOUT)                             .startPayment(getCardPayment(timestamp,Constants.MERCHANT_ID,Constants.SECRET_KEY,requestId,TransactionType.PURCHASE,BigDecimal(amount),"EUR",createPaymentRespModel))**
