### ISSUE TITLE
How to set WDNotification.ipn url in android. 

### ISSUE THREAD

**Issue by chetan1011** [wirecard/paymentSDK-Android#21]
How to set WDNotification.ipn url in android. 

how can we decided a payment successfully transfer in merchant a/c.

**Comment by stefan-sedlak** [comment]
Hi @chetan1011 ,
WDNotification is iOS 2.x SDK class. Do you integrate iOS SDK?

**Comment by chetan1011** [comment]
As I mention above, I integrate SDK in android platform.

in ios WDNotification.ipn url exist.

but how can we se WDNotification.ipn url in android. ?

**Comment by stefan-sedlak** [comment]
here you are example:
https://github.com/wirecard/paymentSDK-Android/blob/b0b8258b51b8ffc9cb8de142c2eef28e5bd0cd47/ecom-examples/src/main/java/com/wirecard/ecom/examples/PaymentObjectProvider.java#L143

Here is Class: https://wirecard.github.io/paymentSDK-Android/api/latest/core/com.wirecard.ecom.model/-notification/index.html

And it can be set to payment object notifications field:
https://wirecard.github.io/paymentSDK-Android/api/latest/core/com.wirecard.ecom.model/-payment/notifications.html

**Comment by chetan1011** [comment]
@stefan-sedlak  Thanks for replay.

as I set notification ArrayList in code, but still I didn't get callback url on my server.

code sample:
val cardPayment = CardPayment.Builder()
            .setSignature(signature)
            .setRequestSignature(createPaymentRespModel?.data?.hash!!)
            .setRequestTimeStamp(timestamp)
            .setMerchantAccountId(merchantID)
            .setRequestId(requestID)
            .setAmount(amount)
            .setTransactionType(transactionType)
            .setCurrency(currency)
            .build()

        val notificationModel=Notification()
        notificationModel.url=createPaymentRespModel?.data?.hash!!
        val notiList=ArrayList<Notification>()
        notiList.add(notificationModel)

        cardPayment.notifications=notiList
        cardPayment.requireManualCardBrandSelection = true
        cardPayment.animatedCardPayment = true
        cardPayment.attempt3d=true

let me know how can I solve this problem.

**Comment by stefan-sedlak** [comment]
Hi @chetan1011 ,
what value do you assign to `notificationModel.url`?
