### ISSUE TITLE
differences in signature generation for IOS and Android

### ISSUE THREAD

**Issue by JoaoRSilverio** [wirecard/paymentSDK-Android#23]
We implemented and tested a PURCHASE request, for now using your test
environment. This payment request is done on Android using
paymentSDK-Android on **https://api-test.wirecard.com** and on iOS using
paymentSDK-iOS on **WDECEnvironmentTEST.**
For both we generate the signature **V2**.

Our issue is that we do not manage to make successful payment on both
platform using the same signature format, we detected that the issue is
related to the **requested_amount** format.
**iOS**:
accepted format: 1, 1.2, 1.23
refused format: 1.00, 1.20

**Android** (2 decimals required):
accepted format: 1.00, 1.20, 1.23
refused format: 1, 1.2

Are we doing something wrong or the accepted signature V2 format is really
different on both platforms?

**Comment by stefan-sedlak** [comment]
Hi @JoaoRSilverio please format amount without trailing zeroes.
Valid amount formats:
* 1.01
* 1.1
* 1

Android curiously works because `BigDecimal` keeps `String` from which it was constructed and keeps trailing zeroes when it is serialized back to `String`. `NSDecimalNumber` serialization does not keep trailing zeroes.
 
Best,
Stefan

**Comment by JoaoRSilverio** [comment]
Hi @stefan-sedlak Thank you for your answer.
But the problem seems to be  on the V2signature generation.
The requested_amount field of the payment object is created in both platforms without trailing zeroes. But if while generating the signature in the backend, we use a trailing zero in the requested_amount field it succeeds in the android SDK while failing on the IOS Sdk,  and if we remove trailing zeros it succeeds in IOS and fails on android.

**Comment by stefan-sedlak** [comment]
Hi @JoaoRSilverio ,
we checked today Android SDK and signature v2 works well without trailing zeroes.
We cannot reproduce the issue.

Could you please provide us:
- SDK version
- Android version
- signature example which does not work?

As signature sshall be generated on server side I guess java code is from server side.
Correct?

Best,
Stefan

**Comment by JoaoRSilverio** [comment]
Thank you for your answer @stefan-sedlak 

> As signature sshall be generated on server side I guess java code is from server side.
>Correct?

yes its server side

- SDK version  "3.4.0"

-  Android Version 8.0.0 (Oreo)

original payment object map
```
request_time_stamp -> 2019-11-04T18:28:59+01:00
merchant_account_id -> cad16b4a-abf2-450d-bcb8-1725a4cef443
transaction_type -> purchase
request_id -> d381812d-b66c-4004-b19e-ea21a263748c
requested_amount -> 1.4
requested_amount_currency -> EUR
```
secret key: b3b131ad-ea7e-48bc-9e71-78d0c6ea579d

resulting signature 
```
SFMyNTYKcmVxdWVzdF90aW1lX3N0YW1wPTIwMTktMTEtMDRUMTg6Mjg6NTkrMDE6MDAKbWVyY2hhbnRfYWNjb3VudF9pZD1jYWQxNmI0YS1hYmYyLTQ1MGQtYmNiOC0xNzI1YTRjZWY0NDMKcmVxdWVzdGVkX2Ftb3VudF9jdXJyZW5jeT1FVVIKdHJhbnNhY3Rpb25fdHlwZT1wdXJjaGFzZQpyZXF1ZXN0X2lkPWQzODE4MTJkLWI2NmMtNDAwNC1iMTllLWVhMjFhMjYzNzQ4YwpyZXF1ZXN0ZWRfYW1vdW50PTEuNAo=.EQldxkHPN60y+15yVPGGaK1QycJ53LtLZ5PIvFULoXw=
```

this signature will only work on IOS

**Comment by stefan-sedlak** [comment]
Hi @JoaoRSilverio ,
the signature seems correct and shall work.
I will ask for gateway logs to find the reason.

Meanwhile how do you create BigDecimal amount in Android app?

Thanks,
Stefan

**Comment by JoaoRSilverio** [comment]
I take the amount string and use it to construct it like this.
``` 
BigDecimal parsedAmount =new BigDecimal(amount).setScale(2);
```

**Comment by stefan-sedlak** [comment]
Ss amount String? If it is parsed from JSON I advise to use String with same format as it was generated for signature.

Please remove setScale(2).

**Comment by JoaoRSilverio** [comment]
@stefan-sedlak Thanks!
removing .setScale(2) solved it.

> Is amount String?

yes
