### ISSUE TITLE
PayPal Payment

### ISSUE THREAD

**Issue by gojkocc** [wirecard/paymentSDK-Android#3]
Hi,

I can't pay with PayPal since a few days with Wirecard SDK for Android (I'm using 2.10.0). iOS SDK is working with some iOS Versions but not with all.. Is there any issue on your side or changes with PayPals API?
I have my own Android project where PayPal was working. When I test mine or your demo app now, it is not possible to pay with PayPal. CreditCard is still working.

Thank you.

Kind regards

**Comment by stefan-sedlak** [comment]
Hi,
investigation has started.
Thanks for filling the issue.

**Comment by gojkocc** [comment]
Samsung Galaxy S8 - 7.0.0
OnePlus 2 - 7.1.2
Google Pixel - 8.0.0
Nexus 6P - 8.1.0

iOS seemed to be kind of random. iPhone 6 with iOS 11.0.2 doesn't work but iPad with the same version worked. We tested it more than once on all devices.

**Comment by stefan-sedlak** [comment]
We have checked PayPal sandbox and we found no issue both Android/iOS.
It will not be caused by paymentSDK as it affects both iOS/Android. They are 2 different implementations.

Do you test on test or prod environment?

According https://www.paypal-status.com/history/production there was no production/sandbox issue on PayPal side.
We are investigating further.

**Comment by gojkocc** [comment]
I tested on the test environment.

**Comment by stefan-sedlak** [comment]
On test environment I can ask for gateway logs.
Please provide me:
MAID + requestId

Can you provide as well steps to reproduce and actual result?
Thanks

**Comment by gojkocc** [comment]
MAID: 40df73b2-7d69-4884-a421-30b08572c69e
RequestID: 0090a08c-924f-4497-85fb-93c4dbe4cc07

I start a PayPal payment with all required fields (like in your demo app). Use a wirecard testaccount for logging into PayPal, pay and wait for the result.

Result is "<html><head><title>404 Not Found</title></head><body><h1>Not Found</h1></body></html>"

**Comment by stefan-sedlak** [comment]
Thanks, I will forward the details to our gateway team.
I guess you use signature v2 format.

**Comment by gojkocc** [comment]
Yes, I do use sign v2. Thank you.

**Comment by stefan-sedlak** [comment]
As quick dirty workaround you can try temporarily signature v1 (if your flow/integration allows it)
I am not sure but it could help.
Signature v1 will be removed in near future, so it is really temporary.
Thanks for all details.

**Comment by gojkocc** [comment]
Just to let you: iOS had just to do with a wrong time on the device

**Comment by stefan-sedlak** [comment]
Apps shall just resend signature generated on server side. Device time shall not affect the result.
Device time is not used by paymentSDK.

**Comment by gojkocc** [comment]
If I use the Signature v1 the PayPal payment works on the test environment. Seems to be an issue with Signature v2. Thanks for your advice.

**Comment by stefan-sedlak** [comment]
Hi @gojkocc,
could please verify the fix on your side?
Signature v2 shall be fixed.
