### ISSUE TITLE
How to Client initialization with hostname?

### ISSUE THREAD

**Issue by patelgaurav4u** [wirecard/paymentSDK-Android#7]
please explain initialization. we can't find in document and also sdk methods.

**Comment by patelgaurav4u** [comment]
Hi,
We have set "test.wirecard.com.sg" and facing issue when use below card detail 
VISA= 4005550000000001 Expiry date=05/2019 CVV=602
with Generic UAT test account Merchant ID and Secret.
![img_9317](https://user-images.githubusercontent.com/2362222/38307377-2cb8d506-3831-11e8-8194-3acd349115a5.jpeg)

**Comment by stefan-sedlak** [comment]
I close the question.
To solve unrelated account configuration issue I will contact you via mail.
